modLoader = "javafml" #mandatory
loaderVersion = "[2,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GNU GPLv3"
[[mods]] #mandatory
modId = "watchedpot" #mandatory
version = "${file.jarVersion}" #mandatory
# A display name for the mod
displayName = "A Watched Pot" #mandatory
authors = "Aeonic" #optional
description = '''A watched block sometimes ticks.'''
[[mixins]]
config="watchedpot.mixins.json"
[[dependencies.watchedpot]] #optional
modId = "neoforge" #mandatory
type = 'required' #mandatory
versionRange = "[20.4,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.watchedpot]]
modId = "minecraft"
type = 'required'
versionRange = "[1.20.4]"
ordering = "NONE"
side = "BOTH"
